- name: "Installing node-exporter"
  hosts: node_exporters
  roles:
    - node_exporter
  become: true
  vars:
    node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz"
  tasks:

  
    - name: "downloading and unzipping the node-exporter file"
      unarchive:
        src: "{{ node_exporter_url }}"
        dest: /opt/
        remote_src: yes

    - name: "Moving file contents"
      command: mv /opt/node_exporter-1.1.2.linux-amd64 /opt/node_exporter


    - name: "Copying file"
      copy:
        src: /opt/node_exporter/node_exporter
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
    
    - name: "Post-Installation - CleanUp"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/opt/node_exporter.tar.gz"
        - "/opt/node_exporter"
